#
# example for configuration blog in docker-compose.yml 
#
  %LOXBERRY_CONTAINER%:
    command:
      - "/bin/bash"
    container_name: "%LOXBERRY_CONTAINER%"
    entrypoint:
      - "/docker-entrypoint.sh"
    environment:
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    hostname: "loxberry"
    image: "%LOXBERRY_IMAGENAME%"
    ipc: "private"
    logging:
      driver: "json-file"
      options: {}
    privileged: true
    security_opt:
      - "label=disable"
    stdin_open: true
    tty: true
    ports:
      - "%DOCKER_NET_TCP_80%:80/tcp"
      - "%DOCKER_NET_TCP_443%:443/tcp"
    volumes:
      - %LOXBERRY_OPT_DIR%:/opt/
    working_dir: "/opt"
